config/routes.rb
Rails.application.routes.draw do
  resources :puppies

end

app/models/puppy.rb
class Puppy < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
  before_action :set_puppy, only: [:show, :edit, :update, :destroy]

  # GET /puppies
  # GET /puppies.json
  def index
    @puppies = Puppy.all
  end

  # GET /puppies/1
  # GET /puppies/1.json
  def show
  end

  # GET /puppies/new
  def new
    @puppy = Puppy.new
  end

  # GET /puppies/1/edit
  def edit
  end

  # POST /puppies
  # POST /puppies.json
  def create
    @puppy = Puppy.new(puppy_params)

    respond_to do |format|
      if @puppy.save
        format.html { redirect_to @puppy, notice: 'Puppy was successfully created.' }
        format.json { render :show, status: :created, location: @puppy }
      else
        format.html { render :new }
        format.json { render json: @puppy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /puppies/1
  # PATCH/PUT /puppies/1.json
  def update
    respond_to do |format|
      if @puppy.update(puppy_params)
        format.html { redirect_to @puppy, notice: 'Puppy was successfully updated.' }
        format.json { render :show, status: :ok, location: @puppy }
      else
        format.html { render :edit }
        format.json { render json: @puppy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puppies/1
  # DELETE /puppies/1.json
  def destroy
    @puppy.destroy
    respond_to do |format|
      format.html { redirect_to puppies_url, notice: 'Puppy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puppy
      @puppy = Puppy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def puppy_params
      params.require(:puppy).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/puppies_helper.rb
module PuppiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitGroup</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
Diego's change.

Anthony's change!!

<%= yield %>

</body>
</html>

app/views/puppies/_form.html.erb
<%= form_for(@puppy) do |f| %>
  <% if @puppy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@puppy.errors.count, "error") %> prohibited this puppy from being saved:</h2>

      <ul>
      <% @puppy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/puppies/edit.html.erb
<h1>Editing Puppy</h1>

<%= render 'form' %>

<%= link_to 'Show', @puppy %> |
<%= link_to 'Back', puppies_path %>

app/views/puppies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Puppies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @puppies.each do |puppy| %>
      <tr>
        <td><%= puppy.name %></td>
        <td><%= puppy.age %></td>
        <td><%= link_to 'Show', puppy %></td>
        <td><%= link_to 'Edit', edit_puppy_path(puppy) %></td>
        <td><%= link_to 'Destroy', puppy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Puppy', new_puppy_path %>

app/views/puppies/new.html.erb
<h1>New Puppy</h1>

<%= render 'form' %>

<%= link_to 'Back', puppies_path %>

app/views/puppies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @puppy.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @puppy.age %>
</p>

<%= link_to 'Edit', edit_puppy_path(@puppy) %> |
<%= link_to 'Back', puppies_path %>